export const products = [
  {
    id: 1,
    title: "THE NORTH FACE",
    desc: "1996 Retro Nuptse Quilted Two-Tone Ripstop and Shell Down Jacket",
    main_img: "/productImages/product_1_main_img.webp",
    img_gallery: [
      "./productImages/product_1_img2.webp",
      "./productImages/product_1_img3.webp",
      "./productImages/product_1_img4.webp",
      "./productImages/product_1_img5.webp",
    ],
    price: 320.54,
    color: "blue",
    editor_note_desc:
      "The '1996 Retro Nuptse' jacket is one of The North Face's best-selling styles, and it's been issued in a variety of colours and finishes over the years. This one's made from durable ripstop and shell, and filled with an insulating down layer. The funnel neckline and VELCRO®-fastening cuffs will help keep out the chill.Profits* from the sale of this item from October 11 to 31 October 2021 will be donated to the MR PORTER Health In Mind Fund powered by Movember to support men’s mental and physical health initiatives.Profits means the sale price of the product, less any applicable sales tax and/or duties, the original cost of the product, and any associated inbound taxes, duties and shipping charges. Movember Europe is a registered charity No.1137948 (England/Wales) SC041981 (Scotland) / Movember Foundation is a registered 501(c)3 non-profit organization. For more information visit MR PORTER Health In Mind.",
    cat: "shoes",
  },
  {
    id: 2,
    title: "KLÄTTERMUSEN",
    desc: "Organic Cotton-Jersey T-Shirt",
    main_img: "/productImages/product_2_main_img.webp",
    img_gallery: [
      "./productImages/product_2_img2.webp",
      "./productImages/product_2_img3.webp",
      "./productImages/product_2_img4.webp",
      "./productImages/product_2_img5.webp",
    ],
    price: 130,
    color: "Black",
    editor_note_desc:
      "Klättermusen's T-shirt is cut for a comfortable fit from smooth organic cotton-jersey with a soft handle. It's minimally branded with a small emblem embroidered at the chest. Wear it as a base layer or on its own.Profits* from the sale of this item from October 11 to 31 October 2021 will be donated to the MR PORTER Health In Mind Fund powered by Movember to support men’s mental and physical health initiatives.Profits means the sale price of the product, less any applicable sales tax and/or duties, the original cost of the product, and any associated inbound taxes, duties and shipping charges. Movember Europe is a registered charity No.1137948 (England/Wales) SC041981 (Scotland) / Movember Foundation is a registered 501(c)3 non-profit organization. For more information visit MR PORTER Health In Mind.",
    cat: "shoes",
  },
  {
    id: 3,
    title: "HOKA ONE ONE",
    desc: "Clifton Edge Rubber-Trimmed Mesh Running Sneakers",
    main_img: "./productImages/product_3_main_img.webp",
    img_gallery: [
      "./productImages/product_3_img2.webp",
      "./productImages/product_3_img3.webp",
      "./productImages/product_3_img4.webp",
      "./productImages/product_3_img5.webp",
    ],
    price: 189,
    color: "blue",
    editor_note_desc:
      "Hoka One One's futuristic fits aren’t just for show - they’re engineered to support your feet. - These 'Clifton Edge' mesh running sneakers create a gliding sensation with each pavement strike - Early-stage Meta-Rockers offer a responsive ride - Geometric heels and rubberised EVA outsoles provide lightweight, cushioned landings. Profits* from the sale of this item from October 11 to 31 October 2021 will be donated to the MR PORTER Health In Mind Fund powered by Movember to support men’s mental and physical health initiatives. **Profits means the sale price of the product, less any applicable sales tax and/or duties, the original cost of the product, and any associated inbound taxes, duties and shipping charges. Movember Europe is a registered charity No.1137948 (England/Wales) SC041981 (Scotland) / Movember Foundation is a registered 501(c)3 non-profit organization. For more information visit MR PORTER Health In Mind.",
    cat: "shoes",
  },
  {
    id: 4,
    title: "SNOW PEAK",
    desc: "Thermal Boa Slim-Fit Polartec Thermal Pro Fleece Jacket",
    main_img: "/productImages/product_4_main_img.webp",
    img_gallery: [
      "/productImages/product_4_img2.webp",
      "/productImages/product_4_img3.webp",
      "/productImages/product_4_img4.webp",
      "/productImages/product_4_img5.webp",
    ],
    price: 296,
    color: "Wax",
    editor_note_desc:
      "Snow Peak's 'Boa' jacket is made from Polartec Thermal Pro® - a soft fleece that's insulating yet breathable. It has practical pouch pockets, a cosy funnel neck and comes in a slim-fit profile, so you can layer it to your liking. Profits* from the sale of this item from October 11 to 31 October 2021 will be donated to the MR PORTER Health In Mind Fund powered by Movember to support men’s mental and physical health initiatives. **Profits means the sale price of the product, less any applicable sales tax and/or duties, the original cost of the product, and any associated inbound taxes, duties and shipping charges. Movember Europe is a registered charity No.1137948 (England/Wales) SC041981 (Scotland) / Movember Foundation is a registered 501(c)3 non-profit organization. For more information visit MR PORTER Health In Mind.",
  },
  {
    id: 5,
    title: "ON SWISS",
    desc: "Cloudrock Waterproof Mesh Hiking Boots",
    main_img: "/productImages/product_5_main_img.webp",
    img_gallery: [
      "/productImages/product_5_img2.webp",
      "/productImages/product_5_img3.webp",
      "/productImages/product_5_img4.webp",
      "/productImages/product_5_img5.webp",
    ],
    price: 320.54,
    color: "Brown",
    editor_note_desc:
      "On develops technology to enhance performance, whether you prefer the road, track or trail. - The label's first speed hiking boots, this lightweight 'Cloudrock' pair is made from two types of mesh to optimise stability and breathability - Wind- and water-resistant membrane ensure they're waterproof, while a 360° rubberised mudguard adds an extra level of protection - Flexible high collars are padded for ankle support and to reduce risk of blistering - Speedboard™ creates energy return and comfortable Zero-Gravity CloudTec® cushioning absorbs shock - Quickly secure laces with the single-pull FlexLock system - Missiongrip™ rubber soles deliver traction on uneven terrain",
  },
  {
    id: 6,
    title: "KLÄTTERMUSEN",
    desc: "Skoll Wool-Blend Fleece Jacket",
    main_img: "/productImages/product_6_main_img.webp",
    img_gallery: [
      "/productImages/product_6_img2.webp",
      "/productImages/product_6_img3.webp",
      "/productImages/product_6_img4.webp",
      "/productImages/product_6_img5.webp",
    ],
    price: 343,
    color: "Black",
    editor_note_desc:
      "The starting point of every Klättermusen garment is fabric development, which is carefully tested and refined as part of the brand's ongoing process. This 'Skoll' fleece jacket is cut from insulating wool-blend fleece and has a funnel neck for extra coverage. The zipped pockets offer secure storage while hiking.",
  },
  {
    id: 7,
    title: "SNOW PEAK",
    desc: "Straight-Leg Selvedge Recycled Jeans",
    main_img: "/productImages/product_7_main_img.webp",
    img_gallery: [
      "/productImages/product_7_img2.webp",
      "/productImages/product_7_img3.webp",
      "/productImages/product_7_img4.webp",
      "/productImages/product_7_img5.webp",
    ],
    price: 231,
    color: "Pitch Black",
    editor_note_desc:
      "Snow Peak's jeans are made from recycled cotton that comes from Guatemala - it's been transformed into a 13.5oz selvedge denim that's both sturdy and comfortable. They're cut for a relaxed-straight fit and are dyed a deep indigo.",
  },
  {
    id: 8,
    title: "DIEMME",
    desc: "Ramon Suede Chelsea Boots",
    main_img: "/productImages/product_8_main_img.webp",
    img_gallery: [
      "/productImages/product_8_img2.webp",
      "/productImages/product_8_img3.webp",
      "/productImages/product_8_img4.webp",
      "/productImages/product_8_img5.webp",
    ],
    price: 373.97,
    color: "Brown",
    editor_note_desc:
      "EXCLUSIVE AT MR PORTER. Taking cues from Chelsea styles, Diemme's 'Ramon' boots have been crafted in Italy from smooth suede and trimmed with rubber so they're extra hard wearing. The cleated Vibram soles offer traction underfoot, while pull tabs make them easy to get on.",
  },
  {
    id: 9,
    title: "MANASTASH",
    desc: "Heavy Snug Thermal Tie-Dye Waffle-Knit Cotton-Jersey T-Shirt",
    main_img: "/productImages/product_9_main_img.webp",
    img_gallery: [
      "/productImages/product_9_img2.webp",
      "/productImages/product_9_img3.webp",
      "/productImages/product_9_img4.webp",
      "/productImages/product_9_img5.webp",
    ],
    price: 120.84,
    color: "Green",
    editor_note_desc:
      "EXCLUSIVE AT MR PORTER.Manastash has revisited one of its signature styles, the 'Heavy Snug Thermal' T-shirt, in a tie-dye print just for us. It's made from smooth cotton-jersey in a casual crew neck profile.",
  },
  {
    id: 10,
    title: "EPPERSON MOUNTAINEERING ",
    desc: "Climb Large Packable Logo-Appliquéd Recycled Nylon-Ripstop Tote Bag0",
    main_img: "/productImages/product_10_main_img.webp",
    img_gallery: [
      "/productImages/product_10_img2.webp",
      "/productImages/product_10_img3.webp",
      "/productImages/product_10_img4.webp",
      "/productImages/product_10_img5.webp",
    ],
    price: 166,
    color: "Blue",
    editor_note_desc:
      "EXCLUSIVE AT MR PORTER. Epperson Mountaineering's designs speak for themselves - they're timeless and packed full of genuinely functional features. Ideal for when you've a bit more to carry, this 'Climb' tote is made from DWR-coated recycled nylon-ripstop and features climbing-spec 'daisy chain' webbing to bolster its durability. It has additional drawstring closures so you can alter the dimensions.",
  },
  {
    id: 11,
    title: "MANASTASH",
    desc: "Tie-Dyed Cotton-Blend Twill Belted Trousers",
    main_img: "/productImages/product_11_main_img.webp",
    img_gallery: [
      "/productImages/product_11_img2.webp",
      "/productImages/product_11_img3.webp",
      "/productImages/product_11_img4.webp",
      "/productImages/product_11_img5.webp",
    ],
    price: 224.96,
    color: "Green",
    editor_note_desc:
      "EXCLUSIVE AT MR PORTER. Manastash's trousers are tie-dyed with a marble effect based on Japanese shibori techniques. Influenced by climbing styles, they're made from durable cotton-blend twill and have roomy, wide legs. The utility-inspired buckled belt can be adjusted to fit over base layers.",
  },
  {
    id: 12,
    title: "MANASTASH",
    desc: "Chilliwack Hemp and Organic Cotton-Blend Jacket",
    main_img: "/productImages/product_12_main_img.webp",
    img_gallery: [
      "/productImages/product_12_img2.webp",
      "/productImages/product_12_img3.webp",
      "/productImages/product_12_img4.webp",
      "/productImages/product_12_img5.webp",
    ],
    price: 285.54,
    color: "blue",
    editor_note_desc:
      "Manastash is committed to responsibly sourcing its fabrics, out of respect for the great outdoors for which it designs. Revisiting one of the label's signature '90s styles, this 'Chilliwack' jacket is made from a hemp and organic cotton-blend and trimmed with sturdy shell at the under sleeve. It's finished with the label's mountain motif on the zip pull and along the placket.",
  },
  {
    id: 13,
    title: "FEAR OF GOD ESSENTIALS",
    desc: "Logo-Print Cotton-Blend Jersey Mock-Neck Sweatshirt",
    main_img: "/productImages/product_13_main_img.webp",
    img_gallery: [
      "/productImages/product_13_img2.webp",
      "/productImages/product_13_img3.webp",
      "/productImages/product_13_img4.webp",
      "/productImages/product_13_img5.webp",
    ],
    price: 320.54,
    color: "Green",
    editor_note_desc:
      "Fear of God Essentials' sweatshirt combines the fit of a hoodie with the classic look of a sweater. It's made from smooth cotton-blend jersey in a mock-neck profile. Wear with jeans or a pair of sweatpants from the line.",
  },
  {
    id: 14,
    title: "FEAR OF GOD ESSENTIALS",
    desc: "4Logo-Print Cotton-Blend Jersey Mock-Neck Sweatshirt",
    main_img: "/productImages/product_14_main_img.webp",
    img_gallery: [
      "/productImages/product_14_img2.webp",
      "/productImages/product_14_img3.webp",
      "/productImages/product_14_img4.webp",
      "/productImages/product_14_img5.webp",
    ],
    price: 95.54,
    color: "Taupe",
    editor_note_desc:
      "Fear of God Essentials' sweatshirt combines the fit of a hoodie with the classic look of a sweater. It's made from smooth cotton-blend jersey in a mock-neck profile. Wear with jeans or a pair of sweatpants from the line.",
  },
  {
    id: 15,
    title: "FEAR OF GOD ESSENTIALS",
    desc: "Logo-Print Cotton-Jersey Polo Shirt",
    main_img: "/productImages/product_15_main_img.webp",
    img_gallery: [
      "/productImages/product_15_img2.webp",
      "/productImages/product_15_img3.webp",
      "/productImages/product_15_img4.webp",
      "/productImages/product_15_img5.webp",
    ],
    price: 71.44,
    color: "Green",
    editor_note_desc:
      "The Fear of God Essentials range is made up of neutral staples you can easily mix and match. Made from soft cotton-jersey, this polo shirt features the brand's reflective moniker at the chest and comes in a classic, regular fit.",
  },
  {
    id: 16,
    title: "FEAR OF GOD ESSENTIALS",
    desc: "Logo-Print Stretch-Jersey Sweatpants",
    main_img: "/productImages/product_16_main_img.webp",
    img_gallery: [
      "/productImages/product_16_img2.webp",
      "/productImages/product_16_img3.webp",
      "/productImages/product_16_img4.webp",
      "/productImages/product_16_img5.webp",
    ],
    price: 94.98,
    color: "Black.",
    editor_note_desc:
      "The Fear of God Essentials range is made up of neutral staples you can easily mix and match. Made from soft cotton-jersey, this polo shirt features the brand's reflective moniker at the chest and comes in a classic, regular fit.",
  },
];

export const productCategories = [
  {
    id: 100,
    title: "THE BOOT ROOM: NEW-SEASON STYLES",
    main_img: "productImages/productCat_100_main_img.webp",
    button_txt: "Shop now",
    cat: "shoes",
  },
  {
    id: 101,
    title:
      "IT'S COAT SEASON: BRAVE THE ELEMENTS IN LIGHTWEIGHT AND WATERPROOF JACKETS",
    main_img: "productImages/productCat_101_main_img.jpg",
    button_txt: "Shop now",
    cat: "Coat",
  },
  {
    id: 102,
    title: "ACNE STUDIOS: SHOP THE AW21 COLLECTION",
    main_img: "/productImages/productCat_102_main_img.jpg",
    button_txt: "Shop now",
    cat: "summer",
  },
  {
    id: 103,
    title: "THE KNITWEAR EDIT: AUTUMN'S FINEST",
    main_img: "/productImages/productCat_103_main_img.jpg",
    button_txt: "Shop now",
    cat: "Luxury",
  },
  {
    id: 104,
    title: "THE KHAKI ROOM: OWN YOUR STYLE",
    main_img: "/productImages/productCat_104_main_img.webp",
    button_txt: "Shop now",
    cat: "khaki",
  },
];
